services:
  pg:
    image: postgres:latest
    ports:
      - "5482:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: orders
    volumes:
      - ./docker:/docker-entrypoit-initdb.d
